### ISSUE TITLE
翻译的如此之烂，亘古未见，Google翻译都舍不得用

### ISSUE THREAD

**Issue by constantine97a** [waylau/Gradle-2-User-Guide#5]
翻译的如此之烂，亘古未见，Google翻译都舍不得用

**Comment by waylau** [comment]
@constantine97a     水平有限，仁兄 可否赐教？或者参与翻译？

**Comment by waylau** [comment]
之前 时间比较仓促，很多章节还没有 review ，应该是存在很多语句不通的情况。近期 正在做 复查。感谢你的 支持
